// Export tous les templates d'email
export {
  EMAIL_TEMPLATES,
  TEMPLATE_ALERTE_CRITIQUE,
  TEMPLATE_ALERTE_IMPORTANTE,
  TEMPLATE_ALERTE_INFO,
  TEMPLATE_DIGEST_HEBDOMADAIRE,
  TEMPLATE_RAPPEL_BAIL,
  TEMPLATE_OBJECTIF_ATTEINT,
  TEMPLATE_IMPORT_TERMINE,
  TEMPLATE_BACKUP_EFFECTUE,
  TEMPLATE_TEST_BIENVENUE,
  TEMPLATE_ECHEANCE_ACTION,
  renderTemplate,
  TEMPLATE_VARIABLES,
} from './emailTemplates';

export type { EmailTemplateName } from './emailTemplates';
